#!/bin/bash
# ==============================================================
# job_recovery.sh — Login-node orchestrator
#
# Reads a recovery plan generated by job_audit.sh and submits
# the appropriate SLURM jobs with correct resource profiles
# and dependency chains. Submits a final audit at the end.
#
# Run from the login node:  bash job_recovery.sh
# ==============================================================

set -euo pipefail

# --- Source shared configuration ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/experiment_config.sh"

# --- User-configurable variables ---
EXPERIMENT="${1:-alexnet_cifar10}"
# TOTAL_CHUNKS, BATCH_SIZE, ACCOUNT, ENV_NAME etc. come from experiment_config.sh
NUM_SAMPLES_PER_CLASS=100
SAMPLES_PER_ATTACK=500

# --- Paths ---
PLAN_FILE="experiments/$EXPERIMENT/recovery_plan.sh"
RECOVERY_DIR="experiments/$EXPERIMENT/recovery_jobs"

if [ ! -f "$PLAN_FILE" ]; then
    echo "ERROR: Recovery plan not found: $PLAN_FILE"
    echo "Run job_audit.sh first to generate a recovery plan."
    exit 1
fi

# --- Load recovery plan ---
source "$PLAN_FILE"

if [ "$RECOVERY_NEEDED" = "false" ]; then
    echo "No recovery needed — all artifacts OK."
    exit 0
fi

echo "=============================================================="
echo "  Recovery for experiment: $EXPERIMENT"
echo "  Plan generated at: $RECOVERY_GENERATED_AT"
echo "=============================================================="

# --- Create recovery_jobs directory ---
mkdir -p "$RECOVERY_DIR"
mkdir -p slurm_out slurm_err

# --- Helper: submit and capture job ID ---
submit_job() {
    local script="$1"
    local deps="$2"
    local sbatch_cmd="sbatch"
    if [ -n "$deps" ]; then
        sbatch_cmd="sbatch --dependency=afterok:${deps}"
    fi
    local output
    output=$($sbatch_cmd "$script")
    local job_id
    job_id=$(echo "$output" | awk '{print $NF}')
    echo "$job_id"
}

# Track job IDs for dependency chain
JOB_A=""
JOB_B_IDS=""
JOB_C_IDS=""
JOB_D_IDS=""
JOB_E=""
JOB_F=""
ALL_JOBS=""

# ==============================================================
# Step A: Training
# ==============================================================
if [ "$RECOVER_STEP_A" = "true" ]; then
    cat > "$RECOVERY_DIR/step_A.sh" << 'STEPA_EOF'
#!/bin/bash
#SBATCH --account=CPU_ACCOUNT_PLACEHOLDER
#SBATCH --cpus-per-task=CPUS_PLACEHOLDER
#SBATCH --time=TIME_PLACEHOLDER
#SBATCH --mem=MEM_PLACEHOLDER
#SBATCH --output=slurm_out/REC_A_train_%A.out
#SBATCH --error=slurm_err/REC_A_train_%A.err

mkdir -p $SLURM_SUBMIT_DIR/slurm_out
mkdir -p $SLURM_SUBMIT_DIR/slurm_err

module load StdEnv/2023 python/3.11.5 scipy-stack/2025a
source ENV_PLACEHOLDER/bin/activate

EXPERIMENT="EXPERIMENT_PLACEHOLDER"

mkdir -p $SLURM_TMPDIR/data/cifar-10-batches-py/
cp -r data/cifar-10-batches-py/* $SLURM_TMPDIR/data/cifar-10-batches-py/ 2>/dev/null || true
mkdir -p $SLURM_TMPDIR/data/cifar-100-python/
cp -r data/cifar-100-python/* $SLURM_TMPDIR/data/cifar-100-python/ 2>/dev/null || true
mkdir -p $SLURM_TMPDIR/data/ILSVRC2012/
cp -r /datashare/imagenet/ILSVRC2012/* $SLURM_TMPDIR/data/ILSVRC2012/ 2>/dev/null || true

python training.py --experiment_name $EXPERIMENT --temp_dir $SLURM_TMPDIR
echo "Step A (training) complete."
STEPA_EOF

    sed -i "s/CPU_ACCOUNT_PLACEHOLDER/$CPU_ACCOUNT/g" "$RECOVERY_DIR/step_A.sh"
    sed -i "s/EXPERIMENT_PLACEHOLDER/$EXPERIMENT/g" "$RECOVERY_DIR/step_A.sh"
    sed -i "s|CPUS_PLACEHOLDER|$A_CPUS|g" "$RECOVERY_DIR/step_A.sh"
    sed -i "s|TIME_PLACEHOLDER|$A_TIME|g" "$RECOVERY_DIR/step_A.sh"
    sed -i "s|MEM_PLACEHOLDER|$A_MEM|g" "$RECOVERY_DIR/step_A.sh"
    sed -i "s|ENV_PLACEHOLDER|$ENV_NAME|g" "$RECOVERY_DIR/step_A.sh"

    JOB_A=$(submit_job "$RECOVERY_DIR/step_A.sh" "")
    ALL_JOBS="$JOB_A"
    echo "[Step A] Training submitted: Job $JOB_A"
fi

# ==============================================================
# Step B: Generate matrices (per chunk)
# ==============================================================
if [ "$RECOVER_STEP_B" = "true" ]; then
    for CHUNK in $RECOVER_STEP_B_CHUNKS; do
        cat > "$RECOVERY_DIR/step_B_chunk_${CHUNK}.sh" << STEPB_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH $B_GPU
#SBATCH --cpus-per-task=$B_CPUS
#SBATCH --time=$B_TIME
#SBATCH --mem=$B_MEM
#SBATCH --output=slurm_out/REC_B_mats_${CHUNK}_%A.out
#SBATCH --error=slurm_err/REC_B_mats_${CHUNK}_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load $MODULES
source $ENV_NAME/bin/activate

EXPERIMENT="$EXPERIMENT"
TASK_ID=$CHUNK
TEMP_DIR=\$SLURM_TMPDIR
ZIP_FILE=\$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/matrices_task_\$TASK_ID.zip

mkdir -p \$SLURM_TMPDIR/data/cifar-10-batches-py/
cp -r data/cifar-10-batches-py/* \$SLURM_TMPDIR/data/cifar-10-batches-py/ 2>/dev/null || true
mkdir -p \$SLURM_TMPDIR/data/cifar-100-python/
cp -r data/cifar-100-python/* \$SLURM_TMPDIR/data/cifar-100-python/ 2>/dev/null || true

mkdir -p \$TEMP_DIR/experiments/\$EXPERIMENT/weights/
cp experiments/\$EXPERIMENT/weights/* \$TEMP_DIR/experiments/\$EXPERIMENT/weights/

if [ -f "\$ZIP_FILE" ]; then
    cp "\$ZIP_FILE" "\$TEMP_DIR/experiments/\$EXPERIMENT/"
    unzip -o "\$TEMP_DIR/experiments/\$EXPERIMENT/matrices_task_\$TASK_ID.zip" -d "\$TEMP_DIR/experiments/\$EXPERIMENT/"
fi

timeout 20m python generate_matrices.py --temp_dir \$TEMP_DIR --experiment \$EXPERIMENT --chunk_id \$TASK_ID --total_chunks $TOTAL_CHUNKS --batch_size $BATCH_SIZE --num_samples_per_class $NUM_SAMPLES_PER_CLASS

cd \$TEMP_DIR/experiments/\$EXPERIMENT
zip -r matrices_task_\$TASK_ID.zip matrices || { echo "Zipping failed"; exit 1; }

cd \$SLURM_SUBMIT_DIR
python -m utils.data_integrity --verify-zip \$TEMP_DIR/experiments/\$EXPERIMENT/matrices_task_\$TASK_ID.zip || { echo "Zip verification failed"; exit 1; }

cp \$TEMP_DIR/experiments/\$EXPERIMENT/matrices_task_\$TASK_ID.zip \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/ || { echo "Failed to copy zip"; exit 1; }
echo "Step B chunk $CHUNK complete."
STEPB_EOF

        DEP=""
        if [ -n "$JOB_A" ]; then
            DEP="$JOB_A"
        fi
        JOB_ID=$(submit_job "$RECOVERY_DIR/step_B_chunk_${CHUNK}.sh" "$DEP")
        JOB_B_IDS="${JOB_B_IDS:+$JOB_B_IDS:}$JOB_ID"
        ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_ID"
        echo "[Step B] Matrices chunk $CHUNK submitted: Job $JOB_ID (depends on: ${DEP:-none})"
    done
fi

# ==============================================================
# Step C: Adversarial examples (per-attack parallel jobs)
# ==============================================================
if [ "$RECOVER_STEP_C" = "true" ]; then
    for ATTACK_NAME in $RECOVER_STEP_C_CHUNKS; do
        cat > "$RECOVERY_DIR/step_C_attack_${ATTACK_NAME}.sh" << STEPC_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH $C_GPU
#SBATCH --cpus-per-task=$C_CPUS
#SBATCH --time=$C_TIME
#SBATCH --mem=$C_MEM
#SBATCH --output=slurm_out/REC_C_${ATTACK_NAME}_%A.out
#SBATCH --error=slurm_err/REC_C_${ATTACK_NAME}_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load $MODULES
source $ENV_NAME/bin/activate

EXPERIMENT="$EXPERIMENT"
ATTACK_NAME="$ATTACK_NAME"

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/
cp experiments/\$EXPERIMENT/weights/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/

mkdir -p \$SLURM_TMPDIR/data/cifar-10-batches-py/
cp -r data/cifar-10-batches-py/* \$SLURM_TMPDIR/data/cifar-10-batches-py/ 2>/dev/null || true
mkdir -p \$SLURM_TMPDIR/data/cifar-100-python/
cp -r data/cifar-100-python/* \$SLURM_TMPDIR/data/cifar-100-python/ 2>/dev/null || true

python generate_adversarial_examples.py --experiment_name \$EXPERIMENT --temp_dir=\$SLURM_TMPDIR --attacks \$ATTACK_NAME --no_auto_test
mkdir -p \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/adversarial_examples/\$ATTACK_NAME/
cp -r \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_examples/\$ATTACK_NAME/* \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/adversarial_examples/\$ATTACK_NAME/ 2>/dev/null || true
echo "Step C attack $ATTACK_NAME complete."
STEPC_EOF

        DEP=""
        if [ -n "$JOB_A" ]; then
            DEP="$JOB_A"
        fi
        JOB_ID=$(submit_job "$RECOVERY_DIR/step_C_attack_${ATTACK_NAME}.sh" "$DEP")
        JOB_C_IDS="${JOB_C_IDS:+$JOB_C_IDS:}$JOB_ID"
        ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_ID"
        echo "[Step C] Attack $ATTACK_NAME submitted: Job $JOB_ID (depends on: ${DEP:-none})"
    done
fi

# ==============================================================
# Step D: Adversarial matrices (per chunk, depends on C)
# ==============================================================
if [ "$RECOVER_STEP_D" = "true" ]; then
    for CHUNK in $RECOVER_STEP_D_CHUNKS; do
        cat > "$RECOVERY_DIR/step_D_chunk_${CHUNK}.sh" << STEPD_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH $D_GPU
#SBATCH --cpus-per-task=$D_CPUS
#SBATCH --time=$D_TIME
#SBATCH --mem=$D_MEM
#SBATCH --output=slurm_out/REC_D_adv_mats_${CHUNK}_%A.out
#SBATCH --error=slurm_err/REC_D_adv_mats_${CHUNK}_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load $MODULES
source $ENV_NAME/bin/activate

EXPERIMENT="$EXPERIMENT"
TASK_ID=$CHUNK
ZIP_FILE="\$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/adv_matrices_task_\$TASK_ID.zip"

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/
cp \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/weights/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_examples/
tar cf - -C \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/adversarial_examples . | tar xf - -C \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_examples

if [ -f "\$ZIP_FILE" ]; then
    cp "\$ZIP_FILE" "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/"
    unzip "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/adv_matrices_task_\$TASK_ID.zip" -d "\$SLURM_TMPDIR/experiments/\$EXPERIMENT/"
fi

timeout 11h python generate_adversarial_matrices.py --experiment_name \$EXPERIMENT --temp_dir \$SLURM_TMPDIR --chunk_id \$TASK_ID --total_chunks $TOTAL_CHUNKS --batch_size $BATCH_SIZE --samples_per_attack $SAMPLES_PER_ATTACK

cd \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
zip -r adv_matrices_task_\$TASK_ID.zip adversarial_matrices/ || { echo "Zipping failed"; exit 1; }

cd \$SLURM_SUBMIT_DIR
python -m utils.data_integrity --verify-zip \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adv_matrices_task_\$TASK_ID.zip || { echo "Zip verification failed"; exit 1; }

cp \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adv_matrices_task_\$TASK_ID.zip \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/ || { echo "Failed to copy zip"; exit 1; }
echo "Step D chunk $CHUNK complete."
STEPD_EOF

        # D depends on A (needs model weights) + all C (needs adv examples)
        DEP=""
        if [ -n "$JOB_A" ]; then
            DEP="$JOB_A"
        fi
        if [ -n "$JOB_C_IDS" ]; then
            DEP="${DEP:+$DEP:}$JOB_C_IDS"
        fi
        JOB_ID=$(submit_job "$RECOVERY_DIR/step_D_chunk_${CHUNK}.sh" "$DEP")
        JOB_D_IDS="${JOB_D_IDS:+$JOB_D_IDS:}$JOB_ID"
        ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_ID"
        echo "[Step D] Adversarial matrices chunk $CHUNK submitted: Job $JOB_ID (depends on: ${DEP:-none})"
    done
fi

# ==============================================================
# Step E: Representation Comparison (depends on A + all B + C + all D)
# ==============================================================
if [ "$RECOVER_STEP_E" = "true" ]; then
    cat > "$RECOVERY_DIR/step_E.sh" << STEPE_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH $E_GPU
#SBATCH --cpus-per-task=$E_CPUS
#SBATCH --time=$E_TIME
#SBATCH --mem=$E_MEM
#SBATCH --output=slurm_out/REC_E_rep_comp_%A.out
#SBATCH --error=slurm_err/REC_E_rep_comp_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load $MODULES
source $ENV_NAME/bin/activate

EXPERIMENT="$EXPERIMENT"

mkdir -p \$SLURM_TMPDIR/data/cifar-10-batches-py/
cp -r data/cifar-10-batches-py/* \$SLURM_TMPDIR/data/cifar-10-batches-py/ 2>/dev/null || true
mkdir -p \$SLURM_TMPDIR/data/cifar-100-python/
cp -r data/cifar-100-python/* \$SLURM_TMPDIR/data/cifar-100-python/ 2>/dev/null || true

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/
cp experiments/\$EXPERIMENT/weights/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/weights/

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/matrices/
for i in \$(seq 0 $(( TOTAL_CHUNKS - 1 ))); do
    if [ -f "experiments/\$EXPERIMENT/matrices_task_\$i.zip" ]; then
        cp experiments/\$EXPERIMENT/matrices_task_\$i.zip \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
        unzip -o \$SLURM_TMPDIR/experiments/\$EXPERIMENT/matrices_task_\$i.zip -d \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
    fi
done

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_examples/
cp -r experiments/\$EXPERIMENT/adversarial_examples/* \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_examples/ 2>/dev/null || true

mkdir -p \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adversarial_matrices/
for i in \$(seq 0 $(( TOTAL_CHUNKS - 1 ))); do
    if [ -f "experiments/\$EXPERIMENT/adv_matrices_task_\$i.zip" ]; then
        cp experiments/\$EXPERIMENT/adv_matrices_task_\$i.zip \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
        unzip -o \$SLURM_TMPDIR/experiments/\$EXPERIMENT/adv_matrices_task_\$i.zip -d \$SLURM_TMPDIR/experiments/\$EXPERIMENT/
    fi
done

echo "All data ready. Starting representation comparison..."
python compare_representations.py --experiment \$EXPERIMENT --temp_dir \$SLURM_TMPDIR --svd_ablation

mkdir -p \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/comparison/
cp -r \$SLURM_TMPDIR/experiments/\$EXPERIMENT/comparison/* \$SLURM_SUBMIT_DIR/experiments/\$EXPERIMENT/comparison/ 2>/dev/null || true
echo "Step E (representation comparison) complete."
STEPE_EOF

    # Build dependency: A + all B + C + all D
    E_DEPS=""
    if [ -n "$JOB_A" ]; then
        E_DEPS="$JOB_A"
    fi
    if [ -n "$JOB_B_IDS" ]; then
        E_DEPS="${E_DEPS:+$E_DEPS:}$JOB_B_IDS"
    fi
    if [ -n "$JOB_C_IDS" ]; then
        E_DEPS="${E_DEPS:+$E_DEPS:}$JOB_C_IDS"
    fi
    if [ -n "$JOB_D_IDS" ]; then
        E_DEPS="${E_DEPS:+$E_DEPS:}$JOB_D_IDS"
    fi
    JOB_E=$(submit_job "$RECOVERY_DIR/step_E.sh" "$E_DEPS")
    ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_E"
    echo "[Step E] Rep. comparison submitted: Job $JOB_E (depends on: ${E_DEPS:-none})"
fi

# ==============================================================
# Step F: LaTeX Tables (depends on E)
# ==============================================================
if [ "$RECOVER_STEP_F" = "true" ]; then
    cat > "$RECOVERY_DIR/step_F.sh" << STEPF_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --cpus-per-task=$F_CPUS
#SBATCH --time=$F_TIME
#SBATCH --mem=$F_MEM
#SBATCH --output=slurm_out/REC_F_latex_%A.out
#SBATCH --error=slurm_err/REC_F_latex_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load $MODULES
source $ENV_NAME/bin/activate

cd \$SLURM_SUBMIT_DIR
mkdir -p tables
python generate_latex_tables.py --output tables/
echo "Step F (LaTeX tables) complete."
STEPF_EOF

    F_DEPS="${JOB_E:-}"
    JOB_F=$(submit_job "$RECOVERY_DIR/step_F.sh" "$F_DEPS")
    ALL_JOBS="${ALL_JOBS:+$ALL_JOBS:}$JOB_F"
    echo "[Step F] LaTeX tables submitted: Job $JOB_F (depends on: ${F_DEPS:-none})"
fi

# ==============================================================
# Final Audit: depends on all submitted jobs
# ==============================================================
cat > "$RECOVERY_DIR/final_audit.sh" << FINALAUDIT_EOF
#!/bin/bash
#SBATCH --account=$ACCOUNT
#SBATCH --time=$AUDIT_TIME
#SBATCH --cpus-per-task=$AUDIT_CPUS
#SBATCH --mem=$AUDIT_MEM
#SBATCH --output=slurm_out/REC_FINAL_AUDIT_%A.out
#SBATCH --error=slurm_err/REC_FINAL_AUDIT_%A.err

mkdir -p \$SLURM_SUBMIT_DIR/slurm_out
mkdir -p \$SLURM_SUBMIT_DIR/slurm_err

module load $MODULES
source $ENV_NAME/bin/activate

EXPERIMENT="$EXPERIMENT"
TOTAL_CHUNKS=$TOTAL_CHUNKS

cd \$SLURM_SUBMIT_DIR

python << 'AUDIT_PY_EOF'
import sys, os, json
sys.path.insert(0, os.environ["SLURM_SUBMIT_DIR"])
from utils.data_integrity import verify_experiment, _print_report
from constants.constants import ATTACKS, DEFAULT_EXPERIMENTS

experiment = os.environ["EXPERIMENT"]
total_chunks = int(os.environ["TOTAL_CHUNKS"])
experiment_dir = os.path.join(os.environ["SLURM_SUBMIT_DIR"], "experiments", experiment)

num_classes = 10
if experiment in DEFAULT_EXPERIMENTS:
    dataset = DEFAULT_EXPERIMENTS[experiment].get("dataset", "cifar10")
    if dataset == "cifar100": num_classes = 100
    elif dataset == "imagenet": num_classes = 1000

report = verify_experiment(
    experiment_dir=experiment_dir, experiment_name=experiment,
    num_classes=num_classes, num_samples_per_class=1000,
    total_chunks=total_chunks, num_samples_rejection_level=10000,
    attacks_list=ATTACKS, sample_ratio=0.1,
)
_print_report(report)

report_path = os.path.join(experiment_dir, "audit_report.json")
with open(report_path, "w") as f:
    json.dump(report, f, indent=2)
print(f"Post-recovery audit report saved to: {report_path}")
AUDIT_PY_EOF

echo "Final audit complete."
FINALAUDIT_EOF

FINAL_AUDIT_JOB=$(submit_job "$RECOVERY_DIR/final_audit.sh" "$ALL_JOBS")
echo ""
echo "[Final Audit] Post-recovery audit submitted: Job $FINAL_AUDIT_JOB (depends on: $ALL_JOBS)"

# ==============================================================
# Summary
# ==============================================================
echo ""
echo "=============================================================="
echo "  Recovery jobs submitted for: $EXPERIMENT"
echo "=============================================================="
echo ""
echo "  Dependency chain:"
[ -n "$JOB_A" ]     && echo "    Step A (Training):            $JOB_A"
if [ -n "$JOB_B_IDS" ]; then
    echo "    Step B (Matrices):            ${JOB_B_IDS//:/, }"
fi
[ -n "$JOB_C_IDS" ] && echo "    Step C (Adv examples):        ${JOB_C_IDS//:/, }"
if [ -n "$JOB_D_IDS" ]; then
    echo "    Step D (Adv matrices):        ${JOB_D_IDS//:/, }"
fi
[ -n "$JOB_E" ]     && echo "    Step E (Rep. comparison):     $JOB_E"
[ -n "$JOB_F" ]     && echo "    Step F (LaTeX tables):        $JOB_F"
echo "    Final Audit:                  $FINAL_AUDIT_JOB"
echo ""
echo "  Monitor with: squeue -u \$USER"
echo "  Generated scripts: $RECOVERY_DIR/"
echo "=============================================================="
